# see http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
# default settings (optional: ldap.server)
spring:
  profiles.active: default
  web.resources:
    # 1 year. Update the corresponding value in MvcConfig if this changes.
    cache.period: 31536000
    add-mappings: false # use our custom mappings instead of the defaults
  main:
    banner-mode: "OFF"
  thymeleaf:
    prefix: classpath:/public/app/
management.server.base-path: /actuator
# NOTE: Increasing the log levels may cause sensitive information to be logged.
#       Appropriate precautions should be taken when doing so.
logging:
  level:
    root: WARN
    com.unboundid: INFO
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.boot: INFO
    org.thymeleaf: WARN
    ch.qos.logback: WARN
log.console: true
PingData.SSO.OIDC:
  enabled: true
  issuer-uri: https://pingauth.internal.darkedges.com
  client-id: pingdirectory-admin-console
  client-secret: pingdirectory-admin-console
#   trust-store-file: /home/console/truststore
#   trust-store-type: JKS
#   trust-store-pin:
#   trust-store-pin-environment-variable:
#   strict-hostname-verification: false
#   trust-all: true
  username-attributes:
    - cn
# log.file: /home/console/console.log
# login.hide-server: false
ldap:
  server: pingdirectory-directory-0.pingdirectory-directory:636
#   init-user: cn=directory manager
#   init-password: password
#   trust-store-file: /home/console/truststore
#   trust-store-type: JKS
#   trust-store-pin:
#   trust-store-pin-environment-variable:
#   file-servlet-name: Instance Root File
#   csd-task-enabled: true
#   csd-destination-folder: csd-files
#   #Note: this setting should not be changed at the moment.
#   profile-destination-folder: profile-files
# branding.custom-folder:
configuration:
  complexity: advanced
--- # development profile-specific settings
spring:
  config.activate.on-profile: development
  thymeleaf.cache: false
server: # server settings for running embedded
  port: 9092
ldap: # initialize login in development
  server: localhost:1636
  init-user: cn=directory manager
  init-password: password
log.console: true
# NOTE: These log levels may cause sensitive information to be logged.
#       Appropriate precautions should be taken when doing so.
logging:
  level:
    root: INFO
    com.unboundid: TRACE
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.thymeleaf: INFO
    ch.qos.logback: DEBUG
configuration:
  complexity: advanced
--- # test profile-specific settings
spring.config.activate.on-profile: test
log.console: true
# NOTE: These log levels may cause sensitive information to be logged.
#       Appropriate precautions should be taken when doing so.
logging:
  level:
    root: DEBUG
    com.unboundid: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.thymeleaf: DEBUG
    ch.qos.logback: DEBUG