apiVersion: v2
appVersion: "1.0"
description: A Helm chart for DarkEdges ForgeRock Operations
name: helm-darkedges-forgerock
version: 0.0.1

dependencies:
- name: vault
  repository: https://helm.releases.hashicorp.com
  version: 0.19.0
  alias: vault
  condition: vault.enabled
- name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.7.1
  alias: certmanager
  condition: certmanager.enabled
- name: ingress-nginx
  repository:  https://kubernetes.github.io/ingress-nginx
  version: 4.0.18
  alias: ingress-nginx
  condition: ingress-nginx.enabled