{{- if .Values.ingress.auth.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ping.fullname". }}-auth-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    cert-manager.io/issuer: "vault-issuer"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Host $host";
      more_set_headers "X-Real-IP $remote_addr";
      more_set_headers "X-Forwarded-For $proxy_add_x_forwarded_for";
      more_set_headers "X-Forwarded-Proto $scheme";
      more_set_headers "X-Forwarded-Host $host";
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.auth.fqdn }}
    secretName: {{ template "ping.fullname". }}-auth-tls
  rules:
  - host: {{ .Values.ingress.auth.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ping.fullname". }}-engine-lb
            port:
              number: 9031
  ingressClassName: nginx
{{- end }}