apiVersion: v1
kind: Service
metadata:
  name: {{ template "ping.fullname". }}-console-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "ping.fullname". }}
    console: enabled
  ports:
    - name: tcp-http
      port: 9999
      targetPort: 9999
{{- if .Values.isStatefulSet }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ping.fullname". }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app: {{ template "ping.fullname". }}
  ports:
    - name: tcp-http
      port: 9999
{{- end }}