---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "ping.serviceAccountName" . }}-role
rules:
- apiGroups: ["batch", "apps", ""]
  resources: ["pods", "services", "jobs"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "ping.serviceAccountName" . }}-role-binding
subjects:
- kind: ServiceAccount
  name:  {{ template "ping.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "ping.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ping.serviceAccountName" . }}