apiVersion: v1
kind: Service
metadata:
  name: {{ template "ping.fullname". }}-engine-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "ping.fullname". }}
    engine: enabled
  ports:
    - name: tcp-http
      port: 9031
      targetPort: 9031
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ping.fullname". }}-engine
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app: {{ template "ping.fullname". }}
  ports:
    - name: tcp-http
      port: 9031