---
global:
  clustered_console:
    enabled: false
    isStatefulSet: false
    replicas: 0
  clustered_engine:
    enabled: false
    isStatefulSet: false
    replicas: 0
  standalone:
    enabled: false
    isStatefulSet: false
    replicas: 0
image:
  imagePullPolicy: IfNotPresent
  repository: darkedges/pingfederate
  tag: 11.2.3
ingress:
  auth:
    enabled: false
    fqdn: null
  console:
    enabled: false
    fqdn: null
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
pingfederate:
  env: null
rbac:
  create: true
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
replicaCount: 1
secrets: null
serviceAccount:
  create: true
  name: null
volumeClaimTemplates:
  data:
    storageClassName: null
    storageSize: 100Mi
waitforservices:
  dbService: null
  ldapService: null