apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ping.fullname". }}-console-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}-console
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
