apiVersion: v1
kind: Service
metadata:
  name: {{ template "ping.fullname". }}-console-lb
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}-console
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "ping.fullname". }}-console
  ports:
    - name: tcp-http
      port: 8080
      targetPort: 8080