apiVersion: v1
kind: Service
metadata:
  name: {{ template "ping.fullname". }}-directory
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}-directory
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app: {{ template "ping.fullname". }}-directory
  ports:
    - name: tcp-ldap
      port: 389
    - name: tcp-https
      port: 443
    - name: tcp-ldaps
      port: 636