---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "ping.fullname". }}-genjks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "ping.fullname". }}-genjks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "ping.fullname". }}-genjks
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ping.fullname". }}
    chart: {{ template "ping.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name:  {{ template "ping.fullname". }}-genjks
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "ping.fullname". }}-genjks
  apiGroup: rbac.authorization.k8s.io